version: '3'
services:

  mariadb:
    build: mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - wpsite
    env_file:
      - .env

  wordpress:
    build: wordpress/
    image: wordpress
    volumes:
      - www-data:/var/www/html/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

  nginx:
    build: nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www-data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - wpsite
    restart: always
    env_file:
      - .env

networks:
  wpsite:
    driver: bridge

volumes:
  db-data:
    driver_opts:
      type: none
      device: ${HOME}/data/db-data
      o: bind
  www-data:
    driver_opts:
      type: none
      device: ${HOME}/data/www-data
      o: bind
